from decimal import Decimal

from sqlalchemy import select

from app.database import SessionLocal
from app.models.category import Category
from app.models.product import Product
from app.utils.seed_categories import seed_categories

SEED_PRODUCTS = [
    {
        "category_slug": "fashion",
        "name": "Classic Cotton Shirt",
        "slug": "classic-cotton-shirt",
        "description": "Breathable cotton shirt for daily wear.",
        "price": "29.99",
        "stock_quantity": 45,
        "image_url": "https://images.unsplash.com/photo-1520975918487-3d3f1a9f4f0b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Everyday Denim Jacket",
        "slug": "everyday-denim-jacket",
        "description": "Layer-ready denim jacket with a relaxed fit.",
        "price": "64.99",
        "stock_quantity": 18,
        "image_url": "https://images.unsplash.com/photo-1472417583565-62e7bdeda490?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Portable Bluetooth Speaker",
        "slug": "portable-bluetooth-speaker",
        "description": "Water-resistant speaker with rich sound for travel.",
        "price": "39.99",
        "stock_quantity": 41,
        "image_url": "https://images.unsplash.com/photo-1570813093999-2a1f8b9a3f3b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Wireless Earbuds",
        "slug": "wireless-earbuds",
        "description": "Compact earbuds with clear audio and charging case.",
        "price": "59.99",
        "stock_quantity": 60,
        "image_url": "https://images.unsplash.com/photo-1591014050693-1a0f5b305d9d?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Classic Polo Tee",
        "slug": "classic-polo-tee",
        "description": "Smart casual polo shirt with a soft finish.",
        "price": "24.50",
        "stock_quantity": 36,
        "image_url": "https://images.unsplash.com/photo-1520975918364-9b1d9a9f3a5b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Slim Fit Jeans",
        "slug": "slim-fit-jeans",
        "description": "Durable denim jeans with a tailored silhouette.",
        "price": "44.99",
        "stock_quantity": 27,
        "image_url": "https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Summer Floral Dress",
        "slug": "summer-floral-dress",
        "description": "Lightweight dress designed for warm days.",
        "price": "39.00",
        "stock_quantity": 22,
        "image_url": "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Lightweight Windbreaker",
        "slug": "lightweight-windbreaker",
        "description": "Packable jacket for daily commuting and travel.",
        "price": "54.95",
        "stock_quantity": 19,
        "image_url": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "fashion",
        "name": "Wool Knit Scarf",
        "slug": "wool-knit-scarf",
        "description": "Soft scarf crafted for cool weather comfort.",
        "price": "19.99",
        "stock_quantity": 31,
        "image_url": "https://images.unsplash.com/photo-1519741499600-1ee8b0a2d6f6?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Smartphone Pro Max",
        "slug": "smartphone-pro-max",
        "description": "Flagship phone with advanced camera and battery life.",
        "price": "899.99",
        "stock_quantity": 14,
        "image_url": "https://images.unsplash.com/photo-1510557880182-3c5a4e6e3a6e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Ultra Light Laptop",
        "slug": "ultra-light-laptop",
        "description": "Portable laptop with vivid display and fast performance.",
        "price": "749.00",
        "stock_quantity": 12,
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Galaxy Tablet",
        "slug": "galaxy-tablet",
        "description": "Slim tablet ideal for work, study, and entertainment.",
        "price": "499.50",
        "stock_quantity": 17,
        "image_url": "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "electronics",
        "name": "Smartwatch Luxe",
        "slug": "smartwatch-luxe",
        "description": "Fitness tracking smartwatch with sleek design.",
        "price": "189.99",
        "stock_quantity": 23,
        "image_url": "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "home-kitchen",
        "name": "Kitchen Mixer Grinder",
        "slug": "kitchen-mixer-grinder",
        "description": "Powerful mixer grinder for everyday cooking needs.",
        "price": "89.99",
        "stock_quantity": 16,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "home-kitchen",
        "name": "High-Speed Blender",
        "slug": "high-speed-blender",
        "description": "Versatile blender for smoothies, soups, and sauces.",
        "price": "69.95",
        "stock_quantity": 20,
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "home-kitchen",
        "name": "Stainless Cookware Set",
        "slug": "stainless-cookware-set",
        "description": "Durable cookware set for modern kitchens.",
        "price": "129.00",
        "stock_quantity": 11,
        "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "home-kitchen",
        "name": "Cordless Vacuum Cleaner",
        "slug": "cordless-vacuum-cleaner",
        "description": "Lightweight vacuum for carpets and hard floors.",
        "price": "149.50",
        "stock_quantity": 15,
        "image_url": "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "home-kitchen",
        "name": "Digital Air Fryer",
        "slug": "digital-air-fryer",
        "description": "Healthy cooking with fast heat circulation.",
        "price": "79.90",
        "stock_quantity": 18,
        "image_url": "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "beauty-personal-care",
        "name": "Gentle Face Wash",
        "slug": "gentle-face-wash",
        "description": "Refreshing cleanser suitable for daily use.",
        "price": "12.99",
        "stock_quantity": 40,
        "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "beauty-personal-care",
        "name": "Hydrating Shampoo",
        "slug": "hydrating-shampoo",
        "description": "Nourishing shampoo for smooth and healthy hair.",
        "price": "14.50",
        "stock_quantity": 34,
        "image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "beauty-personal-care",
        "name": "Elegant Perfume",
        "slug": "elegant-perfume",
        "description": "Long-lasting fragrance with a floral touch.",
        "price": "59.00",
        "stock_quantity": 25,
        "image_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "beauty-personal-care",
        "name": "Glow Serum",
        "slug": "glow-serum",
        "description": "Brightening serum for a radiant complexion.",
        "price": "24.99",
        "stock_quantity": 29,
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "beauty-personal-care",
        "name": "Compact Hair Dryer",
        "slug": "compact-hair-dryer",
        "description": "Quick-dry hair dryer with ergonomic design.",
        "price": "34.90",
        "stock_quantity": 21,
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "books",
        "name": "Mystery Novel",
        "slug": "mystery-novel",
        "description": "An engaging mystery novel for evening reading.",
        "price": "15.99",
        "stock_quantity": 45,
        "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "books",
        "name": "Programming Essentials",
        "slug": "programming-essentials",
        "description": "A practical guide for modern software development.",
        "price": "29.99",
        "stock_quantity": 33,
        "image_url": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "books",
        "name": "Self Help Guide",
        "slug": "self-help-guide",
        "description": "Inspiring book for motivation and personal growth.",
        "price": "18.50",
        "stock_quantity": 27,
        "image_url": "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "books",
        "name": "Healthy Cooking Book",
        "slug": "healthy-cooking-book",
        "description": "Simple recipes for everyday healthy meals.",
        "price": "22.00",
        "stock_quantity": 24,
        "image_url": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "books",
        "name": "Kids Story Collection",
        "slug": "kids-story-collection",
        "description": "A collection of fun stories for young readers.",
        "price": "16.75",
        "stock_quantity": 30,
        "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "sports-fitness",
        "name": "Adjustable Dumbbells",
        "slug": "adjustable-dumbbells",
        "description": "Compact dumbbells for home workouts and strength training.",
        "price": "79.99",
        "stock_quantity": 20,
        "image_url": "https://images.unsplash.com/photo-1558611012-696072aa579a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "sports-fitness",
        "name": "Premium Yoga Mat",
        "slug": "premium-yoga-mat",
        "description": "Non-slip yoga mat for fitness and meditation.",
        "price": "29.00",
        "stock_quantity": 26,
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "sports-fitness",
        "name": "Cricket Bat Deluxe",
        "slug": "cricket-bat-deluxe",
        "description": "High-grade cricket bat for practice and matches.",
        "price": "54.50",
        "stock_quantity": 14,
        "image_url": "https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "sports-fitness",
        "name": "Official Football",
        "slug": "official-football",
        "description": "Durable football designed for outdoor play.",
        "price": "34.99",
        "stock_quantity": 18,
        "image_url": "https://images.unsplash.com/photo-1505842465776-3d4c8f0d0f12?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "sports-fitness",
        "name": "Resistance Bands Set",
        "slug": "resistance-bands-set",
        "description": "Portable bands for stretching and strength workouts.",
        "price": "19.95",
        "stock_quantity": 22,
        "image_url": "https://images.unsplash.com/photo-1594737625785-6d7d49f9a1c7?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "toys-games",
        "name": "LEGO Classic Set",
        "slug": "lego-classic-set",
        "description": "Creative building blocks for endless imagination.",
        "price": "29.99",
        "stock_quantity": 28,
        "image_url": "https://images.unsplash.com/photo-1580712632715-9f1c9f2b1f2a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "toys-games",
        "name": "Family Board Game",
        "slug": "family-board-game",
        "description": "Fun strategy game for family game nights.",
        "price": "24.50",
        "stock_quantity": 32,
        "image_url": "https://images.unsplash.com/photo-1526318472351-c75fcf070b6a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "toys-games",
        "name": "Remote Control Car",
        "slug": "remote-control-car",
        "description": "Speedy RC car with rechargeable battery.",
        "price": "39.90",
        "stock_quantity": 17,
        "image_url": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "toys-games",
        "name": "Puzzle Adventure Set",
        "slug": "puzzle-adventure-set",
        "description": "Challenging puzzle set for kids and adults.",
        "price": "17.99",
        "stock_quantity": 21,
        "image_url": "https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "toys-games",
        "name": "Plush Toy Companion",
        "slug": "plush-toy-companion",
        "description": "Soft plush toy for comfort and playtime.",
        "price": "14.00",
        "stock_quantity": 26,
        "image_url": "https://images.unsplash.com/photo-1516822003754-cca485356ecb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "grocery",
        "name": "Basmati Rice 5kg",
        "slug": "basmati-rice-5kg",
        "description": "Long grain rice for everyday meals.",
        "price": "11.99",
        "stock_quantity": 50,
        "image_url": "https://images.unsplash.com/photo-1496412705862-e0088f16f791?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "grocery",
        "name": "Arabica Coffee Beans",
        "slug": "arabica-coffee-beans",
        "description": "Rich roasted coffee beans for fresh brews.",
        "price": "13.50",
        "stock_quantity": 40,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "grocery",
        "name": "Green Tea Pack",
        "slug": "green-tea-pack",
        "description": "Premium green tea leaves for daily refreshment.",
        "price": "8.99",
        "stock_quantity": 38,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "grocery",
        "name": "Snack Variety Box",
        "slug": "snack-variety-box",
        "description": "Assorted snacks for quick bites and gatherings.",
        "price": "9.50",
        "stock_quantity": 35,
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "grocery",
        "name": "Pure Cooking Oil",
        "slug": "pure-cooking-oil",
        "description": "Versatile cooking oil for everyday meal prep.",
        "price": "7.25",
        "stock_quantity": 42,
        "image_url": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "furniture",
        "name": "Ergonomic Office Chair",
        "slug": "ergonomic-office-chair",
        "description": "Comfortable chair designed for long work sessions.",
        "price": "129.99",
        "stock_quantity": 12,
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "furniture",
        "name": "Study Table",
        "slug": "study-table",
        "description": "Compact study table with practical storage.",
        "price": "99.50",
        "stock_quantity": 10,
        "image_url": "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "furniture",
        "name": "Modern Sofa",
        "slug": "modern-sofa",
        "description": "Stylish sofa for living room comfort.",
        "price": "449.00",
        "stock_quantity": 8,
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "furniture",
        "name": "Wardrobe Storage Unit",
        "slug": "wardrobe-storage-unit",
        "description": "Spacious wardrobe for clothes and accessories.",
        "price": "259.99",
        "stock_quantity": 9,
        "image_url": "https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "furniture",
        "name": "Bedside Table",
        "slug": "bedside-table",
        "description": "Elegant bedside table for bedrooms and reading nooks.",
        "price": "69.95",
        "stock_quantity": 15,
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "office-supplies",
        "name": "Spiral Notebook",
        "slug": "spiral-notebook",
        "description": "Smooth paper notebook for notes and planning.",
        "price": "4.99",
        "stock_quantity": 60,
        "image_url": "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "office-supplies",
        "name": "Premium Pen Set",
        "slug": "premium-pen-set",
        "description": "Set of smooth-writing pens for work and study.",
        "price": "8.50",
        "stock_quantity": 48,
        "image_url": "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "office-supplies",
        "name": "Wireless Printer",
        "slug": "wireless-printer",
        "description": "Compact printer for home and office printing.",
        "price": "159.00",
        "stock_quantity": 11,
        "image_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "office-supplies",
        "name": "LED Desk Lamp",
        "slug": "led-desk-lamp",
        "description": "Adjustable desk lamp for focused work sessions.",
        "price": "29.99",
        "stock_quantity": 24,
        "image_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "category_slug": "office-supplies",
        "name": "Desktop Organizer",
        "slug": "desktop-organizer",
        "description": "Neat storage solution for office essentials.",
        "price": "19.95",
        "stock_quantity": 22,
        "image_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80",
    },
]


def seed_products() -> None:
    seed_categories()
    db = SessionLocal()
    created = 0
    updated = 0
    try:
        categories = {
            category.slug: category
            for category in db.scalars(select(Category).where(Category.is_active.is_(True)))
        }
        for item in SEED_PRODUCTS:
            category = categories[item["category_slug"]]
            product = db.scalar(select(Product).where(Product.slug == item["slug"]))
            product_data = {
                "category_id": category.id,
                "name": item["name"],
                "slug": item["slug"],
                "description": item["description"],
                "price": Decimal(item["price"]),
                "stock_quantity": item["stock_quantity"],
                "image_url": item["image_url"],
                "is_active": True,
            }
            if product:
                for field, value in product_data.items():
                    setattr(product, field, value)
                updated += 1
            else:
                db.add(Product(**product_data))
                created += 1
        db.commit()
        print(f"Products seeded. Created: {created}, updated: {updated}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_products()

